# Generated by Django 5.1.6 on 2025-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_product_is_active_alter_producttype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='product', to='Api.productimage'),
        ),
    ]
