# Generated by Django 5.1.6 on 2025-03-30 22:46

import django.db.models.deletion
import django_userforeignkey.models.fields
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_product_created_by_alter_product_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSeekRequestResponseModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=22, max_length=22, prefix='', primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('response_in_seconds', models.IntegerField(blank=True, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
