# Generated by Django 5.1.6 on 2025-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0008_cartproductitem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartproductitem",
            name="unique_product_cart",
        ),
        migrations.AddConstraint(
            model_name="cartproductitem",
            constraint=models.UniqueConstraint(
                fields=("id", "product", "created_by"), name="unique_product_cart"
            ),
        ),
    ]
